# Generated by Django 5.2.5 on 2025-12-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_genres_user_bio_user_platform_user_public_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_profile',
            field=models.BooleanField(default=False),
        ),
    ]
